import Head from "next/head";
import Image from "next/image";
import List from "../components/List";
import IconCard from "../components/IconCard";
import {
  AdjustmentsIcon,
  ShoppingBagIcon,
  WifiIcon,
  MicrophoneIcon,
} from "@heroicons/react/outline";

export default function Home() {
  return (
    <div className="w-screen h-screen flex justify-center items-center font-main">
      <Head>
        <title>Card</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className=" grid grid-cols-3 shadow-md">
          <div className="w-[400px] h-[400px] relative rounded-l-lg">
            <Image
              src="/headphone.jpg"
              alt="headphone"
              width={400}
              height={400}
              objectFit="cover"
              layout="responsive"
              className="rounded-l-lg"
            />
          </div>
          <div className="text-white absolute bg-[#764013] w-[400px] h-[400px] opacity-75 rounded-l-lg"></div>
          <div className="absolute text-white m-4 space-y-10">
            <h2 className="text-xs">Design by:</h2>
            <h2 className="text-4xl font-bold">Headphone</h2>
            <div className="space-y-5">
              <List feature="High-Resolution Audio compatible" />
              <List feature="Resonance free housing" />
              <List feature="Silver-coated oxygen-free copper cables" />
            </div>
            <button className="text-xs uppercase tracking-wider bg-white text-gray-600 rounded-full px-5 py-3 shadow-sm">
              Learn more
            </button>
          </div>

          <div className="col-span-2 w-[800px]">
            <div className="grid grid-cols-2 grid-rows-2">
              <IconCard title="Microphone" Icon={MicrophoneIcon} />
              <IconCard title="Wifi" Icon={WifiIcon} />
              <IconCard title="Weight" Icon={ShoppingBagIcon} />
              <IconCard title="Adjust" Icon={AdjustmentsIcon} />
            </div>
          </div>
        </div>
      </main>
    </div>
  );
}
